#!/usr/bin/env bash
# Measurement harness for Program 6 (K-Means).
#
#   ./measure_prog6.sh profile    per-phase breakdown, original and final
#   ./measure_prog6.sh variants   serial / by-k / by-m at full thread count
#   ./measure_prog6.sh sweep      by-m across thread counts
#   ./measure_prog6.sh all        all of the above
#
# One run takes 20-50 s, almost all of it inside the timed region, so the
# repetition count is lower here than the 5 used elsewhere in this report.
# RUNS=<n> overrides it. The minimum is reported, as everywhere else.

set -u

RUNS="${RUNS:-3}"
SWEEP_RUNS="${SWEEP_RUNS:-3}"
THREAD_COUNTS="${THREAD_COUNTS:-1 2 3 4 6 8}"

total_ms() { grep -oP '\[Total Time\]: \K[0-9.]+'; }

# best <label> <runs> -- remaining args are VAR=VAL pairs
best() {
    local label="$1" runs="$2"; shift 2
    local b="" ms
    for i in $(seq 1 "$runs"); do
        ms=$(env "$@" ./kmeans 2>/dev/null | total_ms)
        b=$(awk -v a="$b" -v v="$ms" 'BEGIN{ if(a=="" || v<a) print v; else print a }')
        printf "    run %d: %s ms\n" "$i" "$ms" >&2
    done
    echo "$b"
}

# Profiles one variant RUNS times and keeps the breakdown from the fastest
# run. A single profiling run is not safe to trust here: this is a 45 W mobile
# part and a 50 s single-threaded workload heats it enough that a run taken
# straight after another is measurably slower, which would distort the phase
# shares that Amdahl's Law is then applied to.
profile_one() {
    local label="$1"; shift
    local bestSum="" i sum
    rm -f "prog6_profile_${label}.csv"
    for i in $(seq 1 "$RUNS"); do
        env "$@" KMEANS_PROFILE=1 ./kmeans >/dev/null 2>/dev/null
        [ -f prog6_profile.csv ] || { echo "no profile emitted"; return 1; }
        sum=$(awk -F, 'NR>1{s+=$2} END{printf "%.3f", s}' prog6_profile.csv)
        printf "    run %d: %s ms total\n" "$i" "$sum" >&2
        if [ -z "$bestSum" ] || awk -v a="$sum" -v b="$bestSum" \
             'BEGIN{exit !(a<b)}'; then
            bestSum="$sum"
            mv -f prog6_profile.csv "prog6_profile_${label}.csv"
        fi
    done
    rm -f prog6_profile.csv
    echo "  -> kept fastest of $RUNS runs ($bestSum ms)"
    awk -F, 'NR>1{printf "     %-20s %10.1f ms  %6.1f%%\n", $1, $2, 100*$3}' \
        "prog6_profile_${label}.csv"
}

profile() {
    echo "== per-phase breakdown, fastest of $RUNS runs each =="
    echo "  original implementation:"
    profile_one serial KMEANS_VARIANT=serial
    echo
    echo "  final implementation:"
    profile_one final KMEANS_VARIANT=bym
}

# Both of the remaining experiments compare configurations whose runtimes
# differ by tens of seconds, on a mobile CPU that slows measurably as it heats.
# Running all repetitions of one configuration before moving to the next would
# therefore charge the later configurations for the heat generated by the
# earlier ones. Instead each round runs every configuration once, and the
# minimum per configuration is taken across rounds, so thermal drift is shared
# rather than assigned to whoever happens to run last.

run_once() {   # VAR=VAL... -- echoes ms
    env "$@" ./kmeans 2>/dev/null | total_ms
}

variants() {
    echo "== implementation variants, $RUNS interleaved rounds =="
    local out=prog6_variants.csv
    local bs="" bk="" bm="" r ms

    for r in $(seq 1 "$RUNS"); do
        printf "  round %d:" "$r"

        ms=$(run_once KMEANS_VARIANT=serial)
        bs=$(awk -v a="$bs" -v v="$ms" 'BEGIN{print (a==""||v<a)?v:a}')
        printf " serial %s" "$ms"

        ms=$(run_once KMEANS_VARIANT=byk)
        bk=$(awk -v a="$bk" -v v="$ms" 'BEGIN{print (a==""||v<a)?v:a}')
        printf " | byk %s" "$ms"

        ms=$(run_once KMEANS_VARIANT=bym)
        bm=$(awk -v a="$bm" -v v="$ms" 'BEGIN{print (a==""||v<a)?v:a}')
        printf " | bym %s\n" "$ms"
    done

    echo "variant,threads,ms" > "$out"
    echo "serial,1,$bs" >> "$out"
    echo "byk,$(nproc),$bk" >> "$out"
    echo "bym,$(nproc),$bm" >> "$out"

    awk -v s="$bs" -v k="$bk" -v m="$bm" 'BEGIN{
        printf "\n  serial       %10.1f ms\n", s;
        printf "  parallel k   %10.1f ms   %.3fx\n", k, s/k;
        printf "  parallel m   %10.1f ms   %.3fx\n", m, s/m;
    }'
}

sweep() {
    echo "== thread sweep (parallel over m), $SWEEP_RUNS interleaved rounds =="
    local out=prog6_sweep.csv
    local r t ms
    declare -A bestFor

    for r in $(seq 1 "$SWEEP_RUNS"); do
        printf "  round %d:" "$r"
        for t in $THREAD_COUNTS; do
            ms=$(run_once KMEANS_THREADS="$t")
            bestFor[$t]=$(awk -v a="${bestFor[$t]:-}" -v v="$ms" \
                              'BEGIN{print (a==""||v<a)?v:a}')
            printf " %s:%s" "$t" "$ms"
        done
        printf "\n"
    done

    echo "threads,ms" > "$out"
    for t in $THREAD_COUNTS; do
        echo "$t,${bestFor[$t]}" >> "$out"
        printf "  %2s threads: %10s ms\n" "$t" "${bestFor[$t]}"
    done
}

case "${1:-all}" in
    profile)  profile ;;
    variants) variants ;;
    sweep)    sweep ;;
    all)      profile; echo; variants; echo; sweep ;;
    *) echo "usage: $0 [profile|variants|sweep|all]"; exit 1 ;;
esac
