#!/usr/bin/env python3
"""
Figures and LaTeX tables for Program 6, from measure_prog6.sh output.

  prog6_phases.png   where the time goes, before and after
  prog6_sweep.png    measured scaling against the Amdahl bound
  prog6_tables.tex   \\input by the write-up

Amdahl's fraction f is taken from the measured serial profile, not assumed.
"""
import csv, os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
def path(n): return os.path.join(HERE, n)

HW_THREADS = 8
PHASES = ["computeAssignments", "computeCentroids", "computeCost"]
NICE = {"computeAssignments": "computeAssignments",
        "computeCentroids": "computeCentroids",
        "computeCost": "computeCost"}


def read_csv(name):
    p = path(name)
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return list(csv.DictReader(f))


def fmt(x, nd=3):
    return f"{x:.{nd}f}"


def amdahl(f, T):
    return 1.0 / ((1.0 - f) + f / T)


ser = read_csv("prog6_profile_serial.csv")
fin = read_csv("prog6_profile_final.csv")
if ser is None or fin is None:
    raise SystemExit("run ./measure_prog6.sh profile first")

def phase_map(rows):
    return {r["function"]: float(r["total_ms"]) for r in rows}

S = phase_map(ser)
F = phase_map(fin)
ITERS = int(ser[0]["iterations"])
S_TOTAL = sum(S.values())
F_TOTAL = sum(F.values())

# Amdahl's fraction: the share of serial runtime spent in the one function the
# assignment permits us to parallelize.
f = S["computeAssignments"] / S_TOTAL
S_MAX = amdahl(f, HW_THREADS)

variants = read_csv("prog6_variants.csv")
V = {r["variant"]: float(r["ms"]) for r in variants} if variants else {}

sweep = read_csv("prog6_sweep.csv")
if sweep:
    sweep = sorted(({"threads": int(r["threads"]), "ms": float(r["ms"])}
                    for r in sweep), key=lambda r: r["threads"])

baseline = V.get("serial", S_TOTAL)
final = V.get("bym", F_TOTAL)
speedup = baseline / final

# --------------------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.5, 4.3),
                               gridspec_kw={"width_ratios": [1, 1.25]})

colors = ["#d62728", "#1f77b4", "#2ca02c"]
for idx, (label, m, total) in enumerate([("original", S, S_TOTAL),
                                          ("final", F, F_TOTAL)]):
    bottom = 0.0
    for c, ph in zip(colors, PHASES):
        v = m[ph] / 1000.0
        ax1.bar(idx, v, bottom=bottom, color=c, width=0.55,
                label=NICE[ph] if idx == 0 else None)
        if v > 1.5:
            ax1.text(idx, bottom + v / 2, f"{v:.1f}s", ha="center",
                     va="center", fontsize=8.5, color="white")
        bottom += v
    ax1.text(idx, bottom + 0.9, f"{bottom:.1f}s", ha="center", fontsize=9,
             fontweight="bold")

ax1.set_xticks([0, 1])
ax1.set_xticklabels(["original", "final"])
ax1.set_ylabel("time (s, sum over all iterations)")
ax1.set_title("Where the time goes")
ax1.set_ylim(0, S_TOTAL / 1000 * 1.18)
ax1.legend(fontsize=8, loc="upper right")
ax1.grid(alpha=0.3, axis="y")

if sweep:
    ts = [r["threads"] for r in sweep]
    meas = [baseline / r["ms"] for r in sweep]
    ideal = [amdahl(f, t) for t in ts]
    ax2.plot(ts, meas, "o-", color="#1f77b4", label="measured (parallel over m)")
    ax2.plot(ts, ideal, "s--", color="#888888",
             label=f"Amdahl bound, $f = {f:.3f}$")
    ax2.axhline(S_MAX, ls=":", color="#d62728", lw=1.3)
    ax2.text(ts[-1], S_MAX, f" $S_{{max}} = {S_MAX:.2f}$", ha="right",
             va="bottom", fontsize=9, color="#d62728")
    ax2.axhline(2.1, ls=":", color="#2ca02c", lw=1.3)
    ax2.text(ts[0], 2.1, " target $2.1\\times$", ha="left", va="bottom",
             fontsize=9, color="#2ca02c")
    ax2.set_xlabel("threads")
    ax2.set_ylabel("speedup over the original")
    ax2.set_title("Measured scaling against the Amdahl bound")
    ax2.set_xticks(ts)
    ax2.set_ylim(0, max(max(meas), S_MAX) * 1.22)
    ax2.grid(alpha=0.3)
    ax2.legend(fontsize=8, loc="lower right")

fig.tight_layout()
fig.savefig(path("prog6_phases.png"), dpi=150)
plt.close(fig)

# --------------------------------------------------------------------------
lines = []
A = lines.append
_tbl = []
def T(x): _tbl.append(x)
def endtable(name):
    A(r"\newcommand{" + name + "}{%")
    lines.extend(_tbl)
    A("}")
    A("")
    del _tbl[:]

A("% Generated by plot_prog6.py -- do not edit by hand.")
A("")

A(r"\newcommand{\prognSixIters}{" + str(ITERS) + "}")
A(r"\newcommand{\prognSixBaselineMs}{" + fmt(baseline, 1) + "}")
A(r"\newcommand{\prognSixFinalMs}{" + fmt(final, 1) + "}")
A(r"\newcommand{\prognSixSpeedup}{" + fmt(speedup, 2) + "}")
A(r"\newcommand{\prognSixF}{" + fmt(f, 3) + "}")
A(r"\newcommand{\prognSixFPct}{" + fmt(100 * f, 1) + "}")
A(r"\newcommand{\prognSixSmax}{" + fmt(S_MAX, 2) + "}")
A(r"\newcommand{\prognSixSmaxEighty}{" + fmt(0.8 * S_MAX, 2) + "}")
A(r"\newcommand{\prognSixFracOfSmax}{" + fmt(100 * speedup / S_MAX, 1) + "}")
A(r"\newcommand{\prognSixSerialFrac}{" + fmt(1 - f, 3) + "}")
A(r"\newcommand{\prognSixFOverT}{" + fmt(f / HW_THREADS, 4) + "}")
A(r"\newcommand{\prognSixDenom}{" + fmt((1 - f) + f / HW_THREADS, 4) + "}")
if "byk" in V:
    A(r"\newcommand{\prognSixByKMs}{" + fmt(V["byk"], 1) + "}")
    A(r"\newcommand{\prognSixByKSpeedup}{" + fmt(baseline / V["byk"], 2) + "}")
byk_prof = read_csv("prog6_profile_byk.csv")
if byk_prof:
    B = phase_map(byk_prof)
    A(r"\newcommand{\prognSixByKAssignGain}{"
      + fmt(S["computeAssignments"] / B["computeAssignments"], 2) + "}")
    # The untouched phases show how much of that is clock rather than threads.
    untouched = ((S["computeCentroids"] + S["computeCost"]) /
                 (B["computeCentroids"] + B["computeCost"]))
    A(r"\newcommand{\prognSixByKDrift}{" + fmt(100 * (untouched - 1), 0) + "}")
    A(r"\newcommand{\prognSixByKAssignGainAdj}{"
      + fmt(S["computeAssignments"] / B["computeAssignments"] / untouched, 2) + "}")
M_POINTS, N_DIMS, K_CLUSTERS = 1_000_000, 100, 3
DATA_BYTES = M_POINTS * N_DIMS * 8
MEASURED_GBS = 18.176          # Program 5, best sustained DRAM bandwidth

# --- Karp-Flatt -----------------------------------------------------------
# e = (1/S - 1/T) / (1 - 1/T): the serial fraction implied by a measured
# speedup. Comparing it against the f measured directly from the profile
# exposes parallel overhead that Amdahl's Law alone does not show.
def karp_flatt(S, T):
    return (1.0 / S - 1.0 / T) / (1.0 - 1.0 / T)

kf_naive = karp_flatt(speedup, HW_THREADS)
A(r"\newcommand{\prognSixKFNaive}{" + fmt(kf_naive, 3) + "}")
A(r"\newcommand{\prognSixKFNaiveGap}{" + fmt(kf_naive - (1 - f), 3) + "}")

t1 = read_csv("prog6_profile_t1.csv")
if t1 and sweep:
    T1 = phase_map(t1)
    t1_total = sum(T1.values())
    f_t1 = T1["computeAssignments"] / t1_total
    one_ms = next(r["ms"] for r in sweep if r["threads"] == 1)
    eight_ms = min(r["ms"] for r in sweep)
    s_thread = one_ms / eight_ms
    kf_fixed = karp_flatt(s_thread, HW_THREADS)
    A(r"\newcommand{\prognSixFOne}{" + fmt(f_t1, 3) + "}")
    A(r"\newcommand{\prognSixSerialFracOne}{" + fmt(1 - f_t1, 3) + "}")
    A(r"\newcommand{\prognSixSThread}{" + fmt(s_thread, 3) + "}")
    A(r"\newcommand{\prognSixKFFixed}{" + fmt(kf_fixed, 3) + "}")
    A(r"\newcommand{\prognSixKFFixedGap}{" + fmt(kf_fixed - (1 - f_t1), 3) + "}")
A("")

# The loop interchange removes (K-1) passes over the data array. At T = 1 the
# whole of its benefit is visible, so the implied bandwidth can be compared
# against what Program 5 measured on this machine -- a cross-check between two
# independent programs.
if t1:
    orig_iter = S["computeAssignments"] / ITERS
    one_iter = T1["computeAssignments"] / ITERS
    saved_ms = orig_iter - one_iter
    bytes_saved = (K_CLUSTERS - 1) * DATA_BYTES
    implied_gbs = bytes_saved / (saved_ms / 1000.0) / 1e9
    A(r"\newcommand{\prognSixAssignOrigIter}{" + fmt(orig_iter, 1) + "}")
    A(r"\newcommand{\prognSixAssignOneIter}{" + fmt(one_iter, 1) + "}")
    A(r"\newcommand{\prognSixInterchangeSaved}{" + fmt(saved_ms, 1) + "}")
    A(r"\newcommand{\prognSixInterchangeGBs}{" + fmt(implied_gbs, 1) + "}")
    A("")

A(r"\newcommand{\prognSixTargetFrac}{" + fmt(100 * 2.1 / S_MAX, 1) + "}")

# Memory traffic of the ORIGINAL loop order: the data array is M*N doubles and
# the k-outer ordering streams all of it once per centroid. Compared against
# the bandwidth Program 5 measured on this machine.
orig_traffic_ms = K_CLUSTERS * DATA_BYTES / (MEASURED_GBS * 1e9) * 1000
A(r"\newcommand{\prognSixDataMB}{" + fmt(DATA_BYTES / 1e6, 0) + "}")
A(r"\newcommand{\prognSixOrigTrafficMs}{" + fmt(orig_traffic_ms, 0) + "}")
A(r"\newcommand{\prognSixAssignGain}{"
  + fmt(S["computeAssignments"] / F["computeAssignments"], 2) + "}")
if sweep:
    one = next((r for r in sweep if r["threads"] == 1), None)
    bestrow = min(sweep, key=lambda r: r["ms"])
    if one:
        # T = 1 isolates the loop interchange: same code, no threading.
        A(r"\newcommand{\prognSixOneThreadMs}{" + fmt(one["ms"], 1) + "}")
        A(r"\newcommand{\prognSixOneThreadSpeedup}{"
          + fmt(baseline / one["ms"], 2) + "}")
    if one:
        # Threading alone, holding the loop interchange fixed.
        A(r"\newcommand{\prognSixParallelOnly}{"
          + fmt(one["ms"] / final, 2) + "}")
    A(r"\newcommand{\prognSixSweepBestMs}{" + fmt(bestrow["ms"], 1) + "}")
    A(r"\newcommand{\prognSixSweepBestSpeedup}{"
      + fmt(baseline / bestrow["ms"], 2) + "}")
A(r"\newcommand{\prognSixAssignShareAfter}{"
  + fmt(100 * F["computeAssignments"] / F_TOTAL, 1) + "}")
A(r"\newcommand{\prognSixCostShareAfter}{"
  + fmt(100 * F["computeCost"] / F_TOTAL, 1) + "}")
A("")

# --- profile table --------------------------------------------------------
T(r"\begin{table}[H]\centering")
T(r"\caption{Where the " + str(ITERS) + r" iterations spend their time, before "
  r"and after. Times are totals over the whole run, from "
  r"\texttt{CycleTimer} probes around each phase; the fastest of three "
  r"profiling runs is reported.}")
T(r"\label{tab:prog6-profile}")
T(r"\begin{tabular}{lrrrrr}\toprule")
T(r"& \multicolumn{2}{c}{Original} & \multicolumn{2}{c}{Final} & \\")
T(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}")
T(r"Phase & ms & Share & ms & Share & Gain \\\midrule")
for ph in PHASES:
    T(f"\\texttt{{{ph}}} & {fmt(S[ph],1)} & {fmt(100*S[ph]/S_TOTAL,1)}\\% & "
      f"{fmt(F[ph],1)} & {fmt(100*F[ph]/F_TOTAL,1)}\\% & "
      f"{fmt(S[ph]/F[ph],2)}$\\times$ \\\\")
T(r"\midrule")
T(f"Total & {fmt(S_TOTAL,1)} & & {fmt(F_TOTAL,1)} & & "
  f"{fmt(S_TOTAL/F_TOTAL,2)}$\\times$ \\\\")
T(r"\bottomrule\end{tabular}\end{table}")
endtable(r"\prognSixTableProfile")

# --- variants table -------------------------------------------------------
if variants:
    PRETTY = {"serial": ("Original (unmodified)", "none"),
              "byk": ("Parallel over cluster index $k$", f"min(T, K) = 3"),
              "bym": ("Parallel over point index $m$", f"T = {HW_THREADS}")}
    T(r"\begin{table}[H]\centering")
    T(r"\caption{The three implementations, minimum of three runs each. "
      r"All converge in " + str(ITERS) + r" iterations, so all compute the "
      r"same result.}")
    T(r"\label{tab:prog6-variants}")
    T(r"\begin{tabular}{llrr}\toprule")
    T(r"Implementation & Threads used & Time (ms) & Speedup \\\midrule")
    for v in ("serial", "byk", "bym"):
        if v not in V:
            continue
        name, th = PRETTY[v]
        T(f"{name} & {th} & {fmt(V[v],1)} & {fmt(baseline/V[v],2)}$\\times$ \\\\")
    T(r"\midrule")
    T(r"\multicolumn{2}{l}{Amdahl bound $S_{max}$ at $T = 8$} & & "
      + fmt(S_MAX, 2) + r"$\times$ \\")
    T(r"\multicolumn{2}{l}{Handout target} & & $2.10\times$ \\")
    T(r"\bottomrule\end{tabular}\end{table}")
    endtable(r"\prognSixTableVariants")

# --- sweep table ----------------------------------------------------------
if sweep:
    T(r"\begin{table}[H]\centering")
    T(r"\caption{Thread sweep of the final implementation against the Amdahl "
      r"bound computed from the measured $f = " + fmt(f, 3) + r"$. The $T = 1$ "
      r"row exceeds the bound because the loop interchange is an improvement "
      r"to the serial code, which Amdahl's Law does not model.}")
    T(r"\label{tab:prog6-sweep}")
    T(r"\begin{tabular}{rrrr}\toprule")
    T(r"Threads & Time (ms) & Measured speedup & Amdahl bound \\\midrule")
    for r in sweep:
        T(f"{r['threads']} & {fmt(r['ms'],1)} & "
          f"{fmt(baseline/r['ms'],2)}$\\times$ & "
          f"{fmt(amdahl(f, r['threads']),2)}$\\times$ \\\\")
    T(r"\bottomrule\end{tabular}\end{table}")
    endtable(r"\prognSixTableSweep")

with open(path("prog6_tables.tex"), "w") as fh:
    fh.write("\n".join(lines) + "\n")

print("wrote prog6_phases.png, prog6_tables.tex")
print(f"  iterations      : {ITERS}")
print(f"  f (measured)    : {f:.4f}  -> S_max = {S_MAX:.3f}, 0.8*S_max = {0.8*S_MAX:.3f}")
print(f"  baseline        : {baseline:.1f} ms")
print(f"  final           : {final:.1f} ms")
print(f"  speedup         : {speedup:.3f}x  ({100*speedup/S_MAX:.1f}% of S_max)")
print(f"  target 2.1x     : {'MET' if speedup >= 2.1 else 'NOT MET'}")
print(f"  0.8 x S_max     : {'MET' if speedup >= 0.8*S_MAX else 'NOT MET'}")
