#!/usr/bin/env python3
"""
Figure and LaTeX tables for Program 2, built from measure_prog2.sh output.

  prog2_width_sweep.png   instruction count and utilization versus width
  prog2_tables.tex        \\input by the write-up
"""
import csv, os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
def path(n): return os.path.join(HERE, n)


def load(fname, key="width"):
    with open(path(fname)) as f:
        return {int(r[key]): r for r in csv.DictReader(f)}


def figure(widths, div):
    ws = sorted(widths)
    ins = [int(widths[w]["total_vector_instructions"]) for w in ws]
    overall = [float(widths[w]["utilization_pct"]) for w in ws]
    loop = [float(div[w]["loop_util_pct"]) for w in ws]

    fig, (a, b) = plt.subplots(1, 2, figsize=(10.5, 4.2))

    a.plot(ws, ins, marker="o", color="tab:blue")
    ideal = [ins[0] * ws[0] / w for w in ws]
    a.plot(ws, ideal, linestyle=":", color="grey",
           label="Perfect scaling from width 2")
    for w, y in zip(ws, ins):
        a.annotate(f"{y:,}", (w, y), textcoords="offset points",
                   xytext=(0, 9), ha="center", fontsize=8)
    a.set_xscale("log", base=2); a.set_yscale("log", base=2)
    a.set_xticks(ws); a.set_xticklabels([str(w) for w in ws])
    a.xaxis.set_minor_locator(matplotlib.ticker.NullLocator())
    a.set_xlabel("VECTOR_WIDTH"); a.set_ylabel("Total vector instructions")
    a.set_title("Cost falls, but short of the ideal")
    a.grid(alpha=0.3); a.legend(fontsize=8)

    b.plot(ws, overall, marker="s", color="tab:blue",
           label="Measured, whole kernel")
    b.plot(ws, loop, marker="^", linestyle="--", color="tab:red",
           label="Inner loop only")
    for w, y in zip(ws, overall):
        b.annotate(f"{y:.1f}%", (w, y), textcoords="offset points",
                   xytext=(0, 9), ha="center", fontsize=8)
    for w, y in zip(ws, loop):
        b.annotate(f"{y:.1f}%", (w, y), textcoords="offset points",
                   xytext=(0, -14), ha="center", fontsize=8, color="tab:red")
    b.set_xscale("log", base=2)
    b.set_xticks(ws); b.set_xticklabels([str(w) for w in ws])
    b.xaxis.set_minor_locator(matplotlib.ticker.NullLocator())
    b.set_ylim(40, 100)
    b.set_xlabel("VECTOR_WIDTH"); b.set_ylabel("Vector lane utilization (%)")
    b.set_title("Utilization falls as width grows")
    b.grid(alpha=0.3); b.legend(fontsize=8)

    fig.suptitle("Program 2: clampedExpVector, N = 10000 "
                 "(exact simulator counts, not timings)")
    fig.tight_layout()
    fig.savefig(path("prog2_width_sweep.png"), dpi=150)
    plt.close(fig)


def tables(widths, div):
    ws = sorted(widths)
    base = int(widths[ws[0]]["total_vector_instructions"])
    rows = []
    for w in ws:
        r, d = widths[w], div[w]
        n = int(r["total_vector_instructions"])
        rows.append(
            f"{w} & {n:,} & {base/n:.2f}$\\times$ & {int(r['utilized_lanes']):,} & "
            f"{int(r['total_lanes']):,} & {r['utilization_pct']}\\% & "
            f"{d['loop_util_pct']}\\% \\\\".replace(",", "\\,"))
    main = ("\\begin{tabular}{r rr rr rr}\n\\toprule\n"
            "Width & Vector & Reduction & Utilized & Total & Utilization "
            "& Inner-loop \\\\\n"
            " & instructions & vs width 2 & lanes & lanes & (measured) "
            "& utilization \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")

    d0 = div[ws[0]]
    drows = [f"{w} & {int(div[w]['loop_iters']):,} & "
             f"{int(div[w]['lane_capacity']):,} & "
             f"{int(div[w]['lane_capacity']) - int(d0['required_mults']):,} & "
             f"{div[w]['loop_util_pct']}\\% \\\\".replace(",", "\\,")
             for w in ws]
    diverge = ("\\begin{tabular}{r rrrr}\n\\toprule\n"
               "Width & Loop iterations & Lane capacity & Wasted lanes "
               "& Useful \\\\\n\\midrule\n" + "\n".join(drows)
               + "\n\\bottomrule\n\\end{tabular}")

    with open(path("prog2_tables.tex"), "w") as f:
        f.write("% Generated by plot_prog2.py from measure_prog2.sh output.\n"
                "\\newcommand{\\progTwoWidths}{%\n" + main + "}\n\n"
                "\\newcommand{\\progTwoDivergence}{%\n" + diverge + "}\n")


def main():
    widths, div = load("prog2_widths.csv"), load("prog2_divergence.csv")
    figure(widths, div)
    tables(widths, div)
    print("wrote prog2_width_sweep.png and prog2_tables.tex")


if __name__ == "__main__":
    main()
