#!/usr/bin/env python3
"""
Emits prog1_tables.tex from the files measure.sh wrote.  The write-up
\\input's the result, so every number in the PDF is the number the harness
recorded - nothing is transcribed by hand.
"""
import csv, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
def path(n): return os.path.join(HERE, n)

T = [2, 3, 4, 5, 6, 7, 8, 16]


def load(fname):
    if not os.path.exists(path(fname)):
        return {}
    with open(path(fname)) as f:
        return {(r["mode"], r["view"], int(r["threads"])): r
                for r in csv.DictReader(f)}


def speedup_table(view, normal, nice):
    """Speedup and efficiency for both decompositions at one view."""
    rows = []
    for t in T:
        b = normal.get(("block", str(view), t))
        c = normal.get(("cyclic", str(view), t))
        p = nice.get(("cyclic", str(view), t))
        if not (b and c):
            continue
        bs, cs = float(b["speedup"]), float(c["speedup"])
        ps = float(p["speedup"]) if p else None
        rows.append(
            f"{t} & {b['thread_min_ms']} & {bs:.2f} & {bs/t:.2f} & "
            f"{c['thread_min_ms']} & {cs:.2f} & {cs/t:.2f} & "
            + (f"{p['thread_min_ms']} & {ps:.2f} & {ps/t:.2f} \\\\"
               if ps else "-- & -- & -- \\\\"))
    return ("\\begin{tabular}{r rrr rrr rrr}\n\\toprule\n"
            " & \\multicolumn{3}{c}{Block} & \\multicolumn{3}{c}{Row-cyclic}"
            " & \\multicolumn{3}{c}{Row-cyclic, \\texttt{nice -20}} \\\\\n"
            "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}\n"
            "Threads & ms & speedup & eff. & ms & speedup & eff."
            " & ms & speedup & eff. \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")


def priority_table(normal, nice, view=1):
    rows = []
    for t in T:
        a = normal.get(("cyclic", str(view), t))
        b = nice.get(("cyclic", str(view), t))
        if not (a and b):
            continue
        x, y = float(a["speedup"]), float(b["speedup"])
        mark = " $\\star$" if (y - x) / x > 0.10 else ""
        rows.append(f"{t} & {x:.2f} & {y:.2f} & ${100*(y-x)/x:+.1f}\\%${mark} \\\\")
    return ("\\begin{tabular}{r rrr}\n\\toprule\n"
            "Threads & Normal priority & \\texttt{nice -20} & Change \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")


HEAD_RE = re.compile(r"### mode=(\w+) threads=(\d+) view=(\d+)")
THREAD_RE = re.compile(
    r"\[thread\s+(\d+) of\s+(\d+)\]\s+(\w+)\s+(\d+) rows\s+([\d.]+) ms")


def load_threadtimes(fname="prog1_threadtimes.txt"):
    if not os.path.exists(path(fname)):
        return {}
    blocks, key, seen = {}, None, {}
    for line in open(path(fname)):
        h = HEAD_RE.match(line)
        if h:
            if key and seen:
                blocks.setdefault(key, []).append(seen)
            key, seen = (h.group(1), int(h.group(2))), {}
            continue
        m = THREAD_RE.search(line)
        if m and key:
            tid = int(m.group(1))
            if tid in seen:
                blocks.setdefault(key, []).append(seen)
                seen = {}
            seen[tid] = float(m.group(5))
    if key and seen:
        blocks.setdefault(key, []).append(seen)
    return blocks


def balance_table(blocks, threads):
    """Per-thread times, block vs cyclic, from the repetition that set the
    reported minimum."""
    sel = {}
    for mode in ("block", "cyclic"):
        reps = blocks.get((mode, threads))
        if reps:
            sel[mode] = min(reps, key=lambda r: max(r.values()))
    if len(sel) < 2:
        return None
    rows = []
    for tid in range(threads):
        b = sel["block"].get(tid)
        c = sel["cyclic"].get(tid)
        rows.append(f"{tid} & {b:.1f} & {c:.1f} \\\\" if b and c else "")
    stat = []
    for mode in ("block", "cyclic"):
        v = list(sel[mode].values())
        stat.append((min(v), max(v), max(v) / min(v)))
    summary = (f"\\midrule\nslowest & \\textbf{{{stat[0][1]:.1f}}} & "
               f"\\textbf{{{stat[1][1]:.1f}}} \\\\\n"
               f"spread & {stat[0][2]:.1f}$\\times$ & {stat[1][2]:.1f}$\\times$ \\\\")
    return ("\\begin{tabular}{r rr}\n\\toprule\n"
            "Thread & Block (ms) & Row-cyclic (ms) \\\\\n\\midrule\n"
            + "\n".join(r for r in rows if r) + "\n" + summary
            + "\n\\bottomrule\n\\end{tabular}")


def main():
    normal, nice = load("prog1_summary.csv"), load("prog1_summary_nice.csv")
    if not normal:
        raise SystemExit("prog1_summary.csv missing - run ./measure.sh sweep")
    blocks = load_threadtimes()

    out = ["% Generated by make_tables.py from measure.sh output. Do not edit.",
           "\\newcommand{\\progOneSpeedupViewOne}{%",
           speedup_table(1, normal, nice), "}", "",
           "\\newcommand{\\progOneSpeedupViewTwo}{%",
           speedup_table(2, normal, nice), "}", "",
           "\\newcommand{\\progOnePriority}{%",
           priority_table(normal, nice), "}", ""]
    for t in (4, 8):
        tab = balance_table(blocks, t)
        if tab:
            name = "Four" if t == 4 else "Eight"
            out += [f"\\newcommand{{\\progOneBalance{name}}}{{%", tab, "}", ""]

    with open(path("prog1_tables.tex"), "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote prog1_tables.tex")


if __name__ == "__main__":
    main()
