#!/usr/bin/env python3
"""
Figure and LaTeX tables for Program 3, from measure_prog3.sh output.
Prefers the elevated-priority sweep when it exists.

  prog3_tasks.png     speedup versus task count, both views
  prog3_tables.tex    \\input by the write-up
"""
import csv, os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
def path(n): return os.path.join(HERE, n)

CORES, WIDTH = 4, 8
CEILING = CORES * WIDTH


def load(fname):
    if not os.path.exists(path(fname)):
        return {}
    with open(path(fname)) as f:
        return {(int(r["tasks"]), int(r["view"])): r for r in csv.DictReader(f)}


def figure(normal, nice):
    fig, ax = plt.subplots(figsize=(8.2, 5.0))
    style = [(normal, "-", "o", "normal priority"),
             (nice, "--", "^", "nice -20")]
    colours = {1: "tab:blue", 2: "tab:orange"}
    for data, ls, mk, tag in style:
        if not data:
            continue
        for view in (1, 2):
            pts = sorted((t, float(r["task_speedup"]))
                         for (t, v), r in data.items() if v == view)
            if pts:
                ax.plot([p[0] for p in pts], [p[1] for p in pts],
                        linestyle=ls, marker=mk, color=colours[view],
                        label=f"View {view}, {tag}")

    ax.axhline(CEILING, color="red", linestyle=":", linewidth=1.2)
    ax.set_ylim(top=CEILING * 1.12)
    ax.text(2.4, CEILING * 1.02,
            f"Theoretical ceiling  $C \\times W = {CORES} \\times {WIDTH} = {CEILING}$",
            color="red", fontsize=9, va="bottom")
    ax.axvline(8, color="grey", linestyle=":", linewidth=0.8)
    ax.text(8.3, 1.5, "8 hardware\nthreads", fontsize=8, color="grey")

    ax.set_xscale("log", base=2)
    ax.set_xlabel("Tasks launched")
    ax.set_ylabel(r"Speedup over serial ($T_{serial}/T_{tasks}$)")
    ax.set_title("Program 3: speedup versus ISPC task count\n"
                 "1200$\\times$800, 256 iterations, AVX2 8-wide, 4 cores")
    ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
    ax.xaxis.set_minor_locator(matplotlib.ticker.NullLocator())
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    fig.savefig(path("prog3_tasks.png"), dpi=150)
    plt.close(fig)


def sweep_table(data, view):
    rows = []
    for (t, v), r in sorted(data.items()):
        if v != view:
            continue
        sp = float(r["task_speedup"])
        rows.append(f"{t} & {r['tasks_min_ms']} & {r['tasks_max_ms']} & "
                    f"{r['spread_pct']}\\% & {sp:.2f}$\\times$ & "
                    f"{100*sp/CEILING:.0f}\\% \\\\")
    return ("\\begin{tabular}{r rrr rr}\n\\toprule\n"
            "Tasks & Min (ms) & Max (ms) & Spread & Speedup & "
            "of $C{\\times}W$ \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")


# The ISPC-without-tasks time is measured in every sweep invocation, so there
# is one per task count. Reporting an arbitrary one makes the SIMD factor
# disagree with the headline result, which is quoted at REPORT_TASKS. Use that
# row for both, so that SIMD x multi-core reproduces the reported total exactly
# -- all three come from the same invocation and the same serial baseline.
REPORT_TASKS = 200


def simd_row(data, view):
    vals = [(t, r) for (t, v), r in data.items() if v == view]
    if not vals:
        return None
    for t, r in vals:
        if t == REPORT_TASKS:
            return r
    return sorted(vals)[0][1]


def simd_table(data):
    rows = []
    for view in (1, 2):
        r = simd_row(data, view)
        if r is None:
            continue
        sp = float(r["ispc_speedup"])
        rows.append(f"{view} & {r['serial_min_ms']} & {r['ispc_min_ms']} & "
                    f"{sp:.2f}$\\times$ & {100*sp/WIDTH:.0f}\\% \\\\")
    return ("\\begin{tabular}{r rr rr}\n\\toprule\n"
            "View & Serial (ms) & ISPC (ms) & Speedup & of $W = 8$ \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}")


def main():
    normal, nice = load("prog3_summary.csv"), load("prog3_summary_nice.csv")
    if not normal:
        raise SystemExit("run ./measure_prog3.sh sweep first")
    best = nice or normal
    figure(normal, nice)
    with open(path("prog3_tables.tex"), "w") as f:
        f.write("% Generated by plot_prog3.py from measure_prog3.sh output.\n")
        f.write("\\newcommand{\\progThreeSimd}{%\n" + simd_table(best) + "}\n\n")
        # Macros so the prose quotes the same numbers as the table.
        for view, name in ((1, "One"), (2, "Two")):
            r = simd_row(best, view)
            if r is None:
                continue
            sp = float(r["ispc_speedup"])
            f.write(f"\\newcommand{{\\progThreeSimdView{name}}}{{{sp:.2f}}}\n")
            f.write(f"\\newcommand{{\\progThreeSimdView{name}Pct}}"
                    f"{{{100*sp/WIDTH:.0f}}}\n")
        r1, r2 = simd_row(best, 1), simd_row(best, 2)
        if r1 and r2:
            s1, s2 = float(r1["ispc_speedup"]), float(r2["ispc_speedup"])
            f.write(f"\\newcommand{{\\progThreeViewGap}}{{{100*(s1-s2)/s1:.0f}}}\n")
            f.write(f"\\newcommand{{\\progThreeIspcMsViewOne}}"
                    f"{{{float(r1['ispc_min_ms']):.3f}}}\n")
            f.write(f"\\newcommand{{\\progThreeTasksMsViewOne}}"
                    f"{{{float(r1['tasks_min_ms']):.3f}}}\n")
            f.write(f"\\newcommand{{\\progThreeMulticore}}"
                    f"{{{float(r1['ispc_min_ms'])/float(r1['tasks_min_ms']):.2f}}}\n")
            f.write(f"\\newcommand{{\\progThreeTotal}}"
                    f"{{{float(r1['task_speedup']):.2f}}}\n\n")
        for view, name in ((1, "One"), (2, "Two")):
            f.write(f"\\newcommand{{\\progThreeSweepView{name}}}{{%\n"
                    + sweep_table(best, view) + "}\n\n")
    src = "prog3_summary_nice.csv" if nice else "prog3_summary.csv"
    print(f"wrote prog3_tasks.png and prog3_tables.tex (tables from {src})")


if __name__ == "__main__":
    main()
